name: 02-workflow-events
on: 
    - push
    - workflow_dispatch

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "This is workflow is triggered by ${{ github.event_name }} event"

        
        
