name: 05-Activity filters
on: 
   pull_request:
    types:
        - closed
    branches:
        - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Hello
              run: echo "pull request is closed"

