name: 06-Contexts
on:
    - workflow_dispatch

env:
    MY_Workflow_VAR: "workflow"

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display information
              run: |
                echo "Event name ${{github.event_name}}"
                echo "Reference ${{github.ref}}"
                echo "SHA ${{github.sha}}"
                echo "Actor ${{github.actor}}"
                echo "Workflow ${{github.workflow}}"
                echo "Run ID ${{github.run_id}}"
                echo "Run Number ${{github.run_number}}"

            - name: Retrieve Variable
              run: |
                echo " Variable value: ${{ vars.MY_VAR}}"

    echo-data-2:
        runs-on: ubuntu-latest
        steps:
            - name: Env Variable
              run: |
                echo "Env Variable value: $MY_Workflow_VAR"

            





        
  

            
           
