name: 08-variables

on:
    - push
    - workflow_dispatch

env:

    WORKFLOW_VAR: "I am a workflow env var"
    OVERWRITEN: "I will be overwritten"
    UNDEFINED_VAR_WITH_DEFAULT: ${{ vars.UNDEFINED_VAR || 'default value' }}


jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "I am a job env var"
            OVERWRITEN: "I have been overwritten at the job level"
        steps:
            - name: Printing env variables
              env:
                STEP_VAR: "I am a step env var"
                step_var2: "I am a step var"
              run: |
                    echo "Step Env var $STEP_VAR" 
                    echo "Step Env var  $step_var2"
                    echo "Job Env var $JOB_VAR"
                    echo "Workflow Env var $WORKFLOW_VAR"
                    echo "Overwritten Env var $OVERWRITEN"

            - name: Overwrite  Job Varaible
              env:
                OVERWRITEN: "I have been overwritten at the step level"
              run: |
                    echo "Step Env var $OVERWRITEN"

    echo2:
        runs-on: ubuntu-latest
        steps:
            - name: Printing Repository variables
              run: |
                    echo "Repository varaible ${{vars.REPOSITORY_VAR}}"
    echo-prod:
        runs-on: ubuntu-latest
        environment: prod

        steps:
            - name: Printing Environment variables
              run: |
                    echo "Repository varaible ${{vars.REPOSITORY_VAR}}"
                    echo "Repository varaible ${{vars.TARGET_VAR}}"
                    echo "Repository varaible ${{vars.OVERWRITTEN_VAR}}"
    echo-staging:
        runs-on: ubuntu-latest
        environment: staging

        steps:
            - name: Printing Environment variables
              run: |
                    echo "Repository varaible ${{vars.REPOSITORY_VAR}}"
                    echo "Repository varaible ${{vars.TARGET_VAR}}"


    echo-undefined:
        runs-on: ubuntu-latest
        env:
            UNDEFINED_VAR_WITH_DEFAULT: "i am defined"
        steps:
            - name: Print Undefined Variables
              run: |
                    echo "Undefined var with default: ${{env.UNDEFINED_VAR_WITH_DEFAULT}}"




                


