name: 12 - Working with Outputs

on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure
                default: success
        
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.status}}

        steps:
            - name: path 
              run: echo "Path is $GITHUB_OUTPUT_PATH"
            - name: Build
              id: build
              run: echo "status=success" >> "$GITHUB_OUTPUT"



    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy
              run: echo "Build status is ${{ needs.build.outputs.build-status }}"

    






