name: 15-matrices

on:
    workflow_dispatch

jobs:
    backward_compatibility:
        strategy:
            matrix:
                python-version: [3.11, 3.12, 3.14]
                os: [ubuntu-latest, windows-latest]
      
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup python 
              uses: actions/setup-python@v6
              with: 
                python-version: ${{ matrix.python-version }}

            - name: python version & os 
        
              run: |
                python --version
                echo "OS: ${{ matrix.os }}"  

            - name: Create artifact
              run: |
                mkdir -p build
                echo " Python version: ${{ matrix.python-version }} $" > build/artifact.txt
                echo " OS: ${{ matrix.os }} $" >> build/artifact.txt

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                    name: my-artifact-${{ matrix.python-version }}-${{ matrix.os }}
                    path: build/
    
    Collecting-Results:
        runs-on: ubuntu-latest
        needs: backward_compatibility
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                path: build/

    
    Include-Examples:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                color: [red, green]
                shape: [circle, square]
                size: [small, large]
                include:
                    - color: red
                      shape: triangle
                    - opacity: 50 
        name: ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}-${{matrix.opacity}}

        steps:
           - name: Show matrix values
             run: |
                  echo "Color: ${{ matrix.color }}"
                  echo "Shape: ${{ matrix.shape }}"
                  echo "Size: ${{ matrix.size }}"
                  echo "Opacity: ${{ matrix.opacity }}"
          



        
        



          
    
                    

      
            




